# Indicates compatibility version with lifecycle
api = "0.8"

# General metadata about the buildpack that is used be the lifecycle
[buildpack]
  id = "ubi-node-engine"
  name = "Paketo Example Node Engine Buildpack"
  version = "0.0.1"

[metadata]
  [[metadata.dependencies]]
    uri = "https://nodejs.org/dist/v17.9.1/node-v17.9.1-linux-x64.tar.xz"

# The list of stacks that the buildpack itself is compatible with
[[stacks]]
  #id = "io.buildpacks.stacks.bionic"
  id = "com.redhat.stacks.ubi"
  build-image = "localhost/cnbs/ubi-build-image"
  run-image = "localhost/cnbs/ubi-run-image"

