# Indicates compatibility version with lifecycle
api = "0.6"

# General metadata about the buildpack that is used be the lifecycle
[buildpack]
  id = "ubi-node-engine"
  name = "Paketo Example Node Engine Buildpack"
  version = "0.0.1"

[metadata]
  [[metadata.dependencies]]
    uri = "https://nodejs.org/dist/v17.9.1/node-v17.9.1-linux-x64.tar.xz"

  [[ubi-metadata.dependencies]]
    rpm = "https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi8/8/x86_64/appstream/os/Packages/n/nodejs-12.22.12-1.module+el8.6.0+15324+1f2c5d8d.x86_64.rpm"

# The list of stacks that the buildpack itself is compatible with
[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "com.redhat.stacks.ubi"
  build-image = "localhost/cnbs/ubi-build-image"
  run-image = "localhost/cnbs/ubi-run-image"

